version: "3.8"
services:
  web: &web
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
  # just in case
  # webpacker:
  #   <<: *web
  #   command: bin/webpack-dev-server
  #   ports:
  #     - '3035:3035'
  #   volumes:
  #     - .:/app:cached
  #     - bundle:/usr/local/bundle
  #     - node_modules:/app/node_modules
  #     - packs:/app/public/packs
  #   environment:
  #     - NODE_ENV=development
  #     - RAILS_ENV=development
  #     - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
  #   depends_on:
  #     - web
